### PR TITLE
btrfs-image sanitization speed-up for "crc collisions" mode

### PR DESCRIPTION
**Pull request by rot13**
This set of changes makes "crc collisions" sanitization nearly as fast as the "random garbage" mode, by running CRC32C in reverse to calculate collisions.

### CODE REVIEW

**Comment by kdave** [comment]
Thanks!

I've fixed up some minor style issues and added the Author and Signed-off-by tags to the changelog. I'd like to keep some formal trace of who authored the patches so I won't bug you to resubmit the whole patchset just to add your signed-off, please do so next time. You can read more about that in https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin .

**Comment by rot13** [comment]
That's perfect, thank you very much. Sorry for the missing Signed-off-by. I blame the lack of time for not getting acquainted with submission rules.

Should I close the pull request now or leave it to you to close it? I'm not familiar with github customs either :/

**Comment by kdave** [comment]
No problem. Please keep it open, I have set some labels so I can track it until it gets released. We've started using github more and there's not much settled down yet, so we'll have to find out what'll work for both sides.

**Comment by kdave** [comment]
Released.

**Pull request closed without merging**
