### PR TITLE
btrfs-progs: mkfs: add new option --ro-subvol

### PR DESCRIPTION
**Pull request by maharmstone**
Adds an --ro-subvol option to mkfs.btrfs, which allows the creation of read-only subvolumes when using --rootdir.

### CODE REVIEW

**Comment by maharmstone** [comment]
This will hopefully be the last of the --subvol patches.

The BTRFS_INODE_ROOT_ITEM_INIT bit is there to prevent btrfs_check_and_init_root_item in the kernel clearing the flags on mount.

**Comment by DaanDeMeyer** [comment]
Hmm, this approach means that the default subvolume specified with --default-subvol can't be made read-only? Maybe it's better to make --default-subvol operate on an existing --subvol or --ro-subvol to avoid option explosion.

**Comment by maharmstone** [comment]
> Hmm, this approach means that the default subvolume specified with --default-subvol can't be made read-only? Maybe it's better to make --default-subvol operate on an existing --subvol or --ro-subvol to avoid option explosion.

Yeah, I sort of assumed that you'd always want the default subvolume to be RW - but I suppose not, in the case of immutable distributions etc. Maybe something like `--subvol dir:ro,default`, with a colon separating the directory name from the flags?

**Comment by DaanDeMeyer** [comment]
Both approaches are fine with me.

**Comment by adam900710** [comment]
If we're goiing the `--subvol dir:ro` way, I guess we can remove the existing `--default-subvol` option.

IMHO the `--subvol dir:ro,default` looks a little more generic.

**Comment by maharmstone** [comment]
I've pushed a new branch implementing the changes as discussed.

**Comment by DaanDeMeyer** [comment]
All working as expected from my testing

**Comment by yuwata** [comment]
Hm, then we cannot create subvolume containing colon??

**Comment by maharmstone** [comment]
> Hm, then we cannot create subvolume containing colon??

I borrowed the syntax from Docker's `-v` for bind mounts. All characters apart from / and \0 are legal in Linux filenames, so there's no safe choice.
Colons have the advantage that they're not legal in filenames on Windows, so people tend to avoid them even elsewhere.

**Comment by yuwata** [comment]
@maharmstone Thank you for the reply. I just thought the change may cause backward compatibility breakage. Bu I noticed that --subvol is new in the next version. Sorry for the noise.

**Comment by adam900710** [comment]
`devel` branch updated to remove the `--default-subvol` option.

Would you please update your first patch just a little? As now there is no `--default-subvol` option to replace.

Otherwise looks good to me.

**Comment by DaanDeMeyer** [comment]
@adam900710 @maharmstone So in systemd-repart we'll keep `DefaultSubvolume=` as a separate setting because there can only be one default subvolume, which maps more cleanly to a separate setting than a flag. So you could consider keeping `--default-subvol` but instead of creating a new subvolume it would make a subvolume specified with `--subvol` the default one. And then if `--default-subvol` is specified multiple times you'd either override the previous value or fail.

Up to you though, I don't mind either API.

**Comment by maharmstone** [comment]
> @maharmstone Thank you for the reply. I just thought the change may cause backward compatibility breakage. Bu I noticed that --subvol is new in the next version. Sorry for the noise.

No worries. I realized after writing that there's an easy solution, which I've included: changing it so it only looks at the last colon. So you do e.g. `--subvol edge:case:` to specify the directory `edge:case` with no flags.

> `devel` branch updated to remove the `--default-subvol` option.
> 
> Would you please update your first patch just a little? As now there is no `--default-subvol` option to replace.
> 
> Otherwise looks good to me.

Thanks, have done

> @adam900710 @maharmstone So in systemd-repart we'll keep `DefaultSubvolume=` as a separate setting because there can only be one default subvolume, which maps more cleanly to a separate setting than a flag. So you could consider keeping `--default-subvol` but instead of creating a new subvolume it would make a subvolume specified with `--subvol` the default one. And then if `--default-subvol` is specified multiple times you'd either override the previous value or fail.
> 
> Up to you though, I don't mind either API.

I've kept it as it is - I think it's best if we don't introduce two ways of doing things, if it's a new flag.

**Review by adam900710 — APPROVED** [review]
Looks good to me. If the interface is fully determined, I'll merge the PR soon.

I'll leave for several days just in case if you want to change the interface.

**Comment by DaanDeMeyer** [comment]
@adam900710 We're all happy with this API, so would be great if this can be merged, then the corresponding PR in systemd can be merged as well.

**Comment by adam900710** [comment]
Thanks for the feedback. Just to be clear, although merged into `devel` branch, the feature will only be included in the next major release (v6.11).
So if something went wrong we still have some time to fix.

**Pull request merged**
