### PR TITLE
Make scrub summary easier to read

### PR DESCRIPTION
**Pull request by Rafostar**
Currently most btrfs commands separate their output with empty lines which makes them more human readable. The scrub cmd when used with -d arg to show per device information does not. It makes it harder to find values for current disk because they are not separated from each other. This commit adds an empty line after each device summary to make it match other btrfs cmd outputs.

### CODE REVIEW

**Comment by Rafostar** [comment]
This is current output of `btrfs scrub status /mnt`:
```
scrub device /dev/sdb (id 1) status
Scrub started:    Mon Jun  1 09:28:24 2020
Status:           running
Duration:         0:36:18
Time left:        2:52:29
ETA:              Mon Jun  1 12:57:13 2020
Total to scrub:   80.00GiB
Bytes scrubbed:   13.91GiB
Rate:             6.54MiB/s
Error summary:    no errors found
scrub device /dev/sdc (id 2) status
Scrub started:    Mon Jun  1 09:28:24 2020
Status:           running
Duration:         0:36:18
Time left:        3:17:08
ETA:              Mon Jun  1 13:21:52 2020
Total to scrub:   80.00GiB
Bytes scrubbed:   12.44GiB
Rate:             5.85MiB/s
Error summary:    no errors found
scrub device /dev/sdd (id 3) status
Scrub started:    Mon Jun  1 09:28:24 2020
Status:           running
Duration:         0:36:18
Time left:        3:32:15
ETA:              Mon Jun  1 13:36:59 2020
Total to scrub:   81.01GiB
Bytes scrubbed:   11.83GiB
Rate:             5.56MiB/s
Error summary:    no errors found
```

And this is with this commit:
```
scrub device /dev/sdb (id 1) status
Scrub started:    Mon Jun  1 09:28:24 2020
Status:           running
Duration:         0:36:18
Time left:        2:52:29
ETA:              Mon Jun  1 12:57:13 2020
Total to scrub:   80.00GiB
Bytes scrubbed:   13.91GiB
Rate:             6.54MiB/s
Error summary:    no errors found

scrub device /dev/sdc (id 2) status
Scrub started:    Mon Jun  1 09:28:24 2020
Status:           running
Duration:         0:36:18
Time left:        3:17:08
ETA:              Mon Jun  1 13:21:52 2020
Total to scrub:   80.00GiB
Bytes scrubbed:   12.44GiB
Rate:             5.85MiB/s
Error summary:    no errors found

scrub device /dev/sdd (id 3) status
Scrub started:    Mon Jun  1 09:28:24 2020
Status:           running
Duration:         0:36:18
Time left:        3:32:15
ETA:              Mon Jun  1 13:36:59 2020
Total to scrub:   81.01GiB
Bytes scrubbed:   11.83GiB
Rate:             5.56MiB/s
Error summary:    no errors found
```

Having separated disks in scrub makes them much more user friendly.

**Comment by Rafostar** [comment]
For now I have put the empty line inside `print_scrub_dev` function. Not sure if you would prefer it inside this function or in the loops that call this function after it is called?

**Comment by kdave** [comment]
It looks good with the blank line and after UUID it would make the 1st device section visibly separated, for clarity.

**Comment by Rafostar** [comment]
@kdave 
I updated the commit to place empty line before printing "scrub device" info (this should also add empty line after UUID like you wanted). I also changed this single line letter case in another commit, cause for some reason it was the only line in scrub status that did not start from capital letter.

**Comment by kdave** [comment]
Merged to devel, thanks.

**Pull request closed without merging**
