### PR TITLE
Fix false positives in log tree checking

### PR DESCRIPTION
**Pull request by maharmstone**
Filipe reported that btrfs/056 was failing due to some false positives reported by the new log-checking code in `btrfs check`.

### CODE REVIEW

**Comment by boryas** [comment]
btrfs/192 is broken on this as far as I can tell, and this PR helps (we get through replaying more of the FUAs) but doesn't fully fix it. Can you investigate that one as well, please? Hopefully there are still a few more kinks in the log csum checking, rather than a real btrfs bug.

**Comment by fdmanana** [comment]
Btw, "sparse extents" is not valid terminology on Linux. We have sparse files, which are files with holes, and holes are regions of a file without extents.

**Comment by maharmstone** [comment]
Thank you Filipe. Yes, that should probably read something like "explicit holes".

**Comment by adam900710** [comment]
The 3 patches looks good to me.
But can we have some images to prevent false alerts from happening again?

**Pull request merged**
