### PR TITLE
Makefile: fix#214 libbtrfs : missing objects

### LINKED ISSUE #214: Missing symbol write_raid56_with_parity
Hello,

libbtrfs version 5.3 requires an undefined symbol `write_raid56_with_parity` and breaks application using it like snapper[1].
```
$ nm -D /usr/lib/libbtrfs.so.0.1|grep raid
                 U write_raid56_with_parity
```

Looks like commit e2da195a3c624b5e862207637e1164b96ed9ccc5 added `extent_io.c` code to libbtrfs which requires this symbol. 

[1] https://bugs.archlinux.org/task/64216

### PR DESCRIPTION
**Pull request by julien-noblet**
Should Fix #214

### CODE REVIEW

**Comment by maximbaz** [comment]
Believe it or not, even this doesn't fully fix the issue for me...

```
❯ snapper --version
snapper: symbol lookup error: /usr/lib/libbtrfs.so.0: undefined symbol: add_to_free_space_tree

❯ ldd -r /usr/lib/libbtrfs.so.0
	linux-vdso.so.1 (0x00007ffde03d7000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f29fda0d000)
	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f29fd9b7000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f29fd995000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f29fd7ce000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f29fda9b000)
undefined symbol: add_to_free_space_tree	(/usr/lib/libbtrfs.so.0)
undefined symbol: btrfs_util_is_subvolume	(/usr/lib/libbtrfs.so.0)
undefined symbol: btrfs_add_corrupt_extent_record	(/usr/lib/libbtrfs.so.0)
undefined symbol: btrfs_insert_inode_ref	(/usr/lib/libbtrfs.so.0)
undefined symbol: btrfs_insert_inode	(/usr/lib/libbtrfs.so.0)
undefined symbol: remove_from_free_space_tree	(/usr/lib/libbtrfs.so.0)
```

**Comment by julien-noblet** [comment]
@maximbaz Can you retry with this patch?

**Comment by maximbaz** [comment]
Fix confirmed (on Arch Linux), thank you very much!

```
❯ snapper --version
snapper 0.8.4
```

**Comment by kdave** [comment]
Thanks, the fix needs to be a bit more convoluted so the newly added .o files don't add new exported symbols. The branch v5.3.x contains all the patches and unless I find more issues, that's going to be released in a day or so.

**Comment by kdave** [comment]
And I did find more, the CI environment reported missing reallocarray so one more file had to be added to the object list. All fixed in 5.3.1.

**Pull request closed without merging**
