### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by LebedevRI**
@kdave as requested.

This may need further refinements, but it already does work: https://travis-ci.org/LebedevRI/btrfs-progs

### CODE REVIEW

**Comment by kdave** [comment]
Thanks. I've experimented a bit, to connect it with coverity, but it does not seem to work (yet). I've managed to remove the docker dependency, as it's not necessary, any standard distro image should suffice.
NB: The coverity project had to be tied to a github account (to make it work with travis) which now looks like it's my project (btrfs-progs -> kdave/btrfs-progs). I don't like that, so I might end up just with the travis build.

**Comment by LebedevRI** [comment]
Whatever works for you.
I'm just glad to be of any help :)

(should i close this ?)

**Comment by kdave** [comment]
Let me keep it open as a reminder.

**Comment by kdave** [comment]
.yml added to devel, closing.

**Pull request closed without merging**
