### PR TITLE
Fixes merge for #59, #174, and #175

### PR DESCRIPTION
**Pull request by unquietwiki**
@kdave this seems like a lot; but honestly, I've made worse commits to other projects. The only one that I'm actually iffy on is the **utils.c** changes: the fallthrough method I borrowed appears to be a [port of what happens in C++17](https://infektor.net/posts/2017-01-19-using-cpp17-attributes-today.html), but might still need yours/their sign off.

- #59 "fix"
- #175 patch from @elliotclee
- #174 fixes: without the other two included, it's kinda silly.

### CODE REVIEW

**Comment by unquietwiki** [comment]
And I've been using this changeset live on a ~90TB recovery effort. My problem so far has been getting my NFS target to absorb the amount of data I'm throwing at it! 💯

**Comment by unquietwiki** [comment]
@kdave Checking back on this: memory usage on my restore project has been pretty consistent; not seeing any major memory leakage. I do notice it's a lot more responsive to restore onto an SMB mount than an NFS mount (keeps overloading the latter).

**Comment by unquietwiki** [comment]
@kdave did any of these changes make it into 5.3.x ? I saw there was mention of "printf fixes" that I do recall working on.

**Comment by kdave** [comment]
#175 has been merged, the other two partially so fart

**Comment by unquietwiki** [comment]
Hey @kdave did you need anything else from https://github.com/unquietwiki/btrfs-progs , or can I delete my copy? I figure you have what you needed. Thanks!

**Pull request closed without merging**
