### PR TITLE
btrfs-progs: check: check order of inline extent refs

### PR DESCRIPTION
**Pull request by maharmstone**
The kernel seems to order inline extent items in a particular way: forward by sub-type, then reverse by hash. Having these out of order can cause a volume to go readonly when deleting an inode.

See https://github.com/maharmstone/ntfs2btrfs/issues/51

### CODE REVIEW

**Comment by kdave** [comment]
@adam900710 Qu can you please have a look?

**Comment by adam900710** [comment]
@maharmstone  Do you still have such bad fs or could you craft one?
We'd like to have a test case for such case.

The patch itself looks goot to me though.

Thanks for exposing the bug!

**Comment by adam900710** [comment]
I checked the kernel code, and indeed `lookup_inline_extent_backref()` is skipping the remaining backref item if data/metadata item is smaller (either through the data hash, or metadata parent/ref_root) than the target range.

Thus it indeed requires the full order inside the inline extent backref.

But we still need the following two things:

- Also detect such problem in lowmem mode

- A test case for it

  For test case, do you still have such image?
  If not, I can help to craft such image if you don't have spare time.
  The same for lowmem mode detection support.

**Comment by maharmstone** [comment]
@adam900710, have a look at @sleirsgoevy's comment in the issue I linked, which gives you the steps to create a test case. Make sure you use ntfs2btrfs 20220812, as it's been fixed since.

**Comment by kdave** [comment]
I've merged the pull request. We don't have the test case and as said above lowmem mode is probably not fixed, but I'd like to move forward with this PR. I've updated the changelog with remaining issues so it's not completely forgotten.

**Comment by maharmstone** [comment]
Thanks Dave

**Comment by adam900710** [comment]
I'll handle the lowmem mode part along with the image part.

Great work exposing the hidden restrict @maharmstone .

For the image part, I guess I had to go some custom `btrfs-corrupt-block` to create a minimal image.
Overall it shouldn't be that hard.

Maybe I can even add tree-checker for the problem, so that the next time we hit such situation, kernel would give a more detailed output to expose such corrupted fs.

**Comment by adam900710** [comment]
Follow ups for progs are here:
https://lore.kernel.org/linux-btrfs/cover.1697945679.git.wqu@suse.com/

The image is hand crafted with 3 inline data backref items, and switched the firsst 2.

**Comment by kdave** [comment]
Thanks, fix added to devel.

**Pull request closed without merging**
